%%%% TASK 3 SCRIPT %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Incorporating a Gaussian tone burst into the acoustic field simulations.
% To simulate a linear filter that suppresses those frequency components
% not present in the pulse shape of finite duration in time.
%
% The pressure s(x,y,z,t) generated by an excitation signal of finite temporal
% duration is obtained by convolving impulse response p and excitation
% function G.
%
% Using the same parameters in Task 1 and function
% comp_press_field_point_source to compute p(x,y,z,t).
% Using the same parameters in Task 2 and function comp_Gaussian_tone_burst
% to compute G(t;f_0,sigma).
%
% 
%
% Return plot - resulting pressure against time with both p(x,y,z,t) and
% s(x,y,z,t) in the same plot
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%

clearvars;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Compute impulse response p(x,y,z,t) %%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% set parameters from Task 1

% set pressure grid point [mm]
x = 1; y = 1; z = 0;
% set point source grid point [mm] 
xs = 0; ys = 0; zs = 0;
% set speed of sound [mm/s]
c = 1500E3;
% set initial acoustic pressure [Pa*mm]
p_0 = 1E3;
% set temporal step size [s]
delta_t = 10E-9;
% create array of time points in range 0<=t<=3 with temporal step size
% delta_t [s]
t_p = (0:delta_t:3E-6);

% calculate impulse response
imp_resp = comp_press_field_point_source(c,p_0,x,y,z,xs,ys,zs,t_p,delta_t);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Compute excitation function G(t;f_0,sigma) %%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% set parameters from Task 2

% set centre frequency [Hz]
f_0 = 10E6;
% set standard deviation [s]
sigma = 50E-9;
% set temporal step size [s]
delta_t = 10E-9;
% set time range using approximation -4*stdev <= t <= +4*stdev
t_G = (-4*sigma:delta_t:4*sigma);

% calculate excitation function
exc_fn = comp_Gaussian_tone_burst(f_0,sigma,delta_t);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Compute pressure generated by an excitation signal of finite duration
%%%% in time %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% by convolving impulse response p and excitation function G over time
s = conv(imp_resp(:),exc_fn,'same');



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Plot resulting pressure against time %%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

figure;
hold on;

% plotting both impulse response and pressure generated by an excitation
% function in the same figure
plot(t_p,imp_resp(:));
plot(t_p,s(:)'); % note: plotting the transpose of s

xlabel('Time [s]');
ylabel('Pressure [Pa]');
title('Pressure as function of time for an acoustic point source');
legend('p(x,y,z,t) - impulse response','s(x,y,z,t) - pressure generated by an excitation signal','location','southoutside');




